window.QUESTION_BANK = {
  wortart: [
    { question: "Hund", options: ["Artikel", "Nomen", "Adjektiv", "Verb"], answer: "Nomen", explanation: "Hund ist ein Nomen." },
    { question: "Haus", options: ["Artikel", "Nomen", "Adjektiv", "Verb"], answer: "Nomen", explanation: "Haus ist ein Nomen." },
    { question: "gehen", options: ["Artikel", "Nomen", "Adjektiv", "Verb"], answer: "Verb", explanation: "gehen ist ein Verb." },
    { question: "gut", options: ["Artikel", "Nomen", "Adjektiv", "Verb"], answer: "Adjektiv", explanation: "gut ist ein Adjektiv." },
    { question: "klein", options: ["Artikel", "Nomen", "Adjektiv", "Verb"], answer: "Adjektiv", explanation: "klein ist ein Adjektiv." },
    { question: "Katze", options: ["Artikel", "Nomen", "Adjektiv", "Verb"], answer: "Nomen", explanation: "Katze ist ein Nomen." },
    { question: "Brot", options: ["Artikel", "Nomen", "Adjektiv", "Verb"], answer: "Nomen", explanation: "Brot ist ein Nomen." },
    { question: "Kind", options: ["Artikel", "Nomen", "Adjektiv", "Verb"], answer: "Nomen", explanation: "Kind ist ein Nomen." },
    { question: "spielen", options: ["Artikel", "Nomen", "Adjektiv", "Verb"], answer: "Verb", explanation: "spielen ist ein Verb." },
    { question: "alt", options: ["Artikel", "Nomen", "Adjektiv", "Verb"], answer: "Adjektiv", explanation: "alt ist ein Adjektiv." },
    { question: "Baum", options: ["Artikel", "Nomen", "Adjektiv", "Verb"], answer: "Nomen", explanation: "Baum ist ein Nomen." },
    { question: "Tisch", options: ["Artikel", "Nomen", "Adjektiv", "Verb"], answer: "Nomen", explanation: "Tisch ist ein Nomen." },
    { question: "Wasser", options: ["Artikel", "Nomen", "Adjektiv", "Verb"], answer: "Nomen", explanation: "Wasser ist ein Nomen." },
    { question: "sehen", options: ["Artikel", "Nomen", "Adjektiv", "Verb"], answer: "Verb", explanation: "sehen ist ein Verb." },
    { question: "groß", options: ["Artikel", "Nomen", "Adjektiv", "Verb"], answer: "Adjektiv", explanation: "groß ist ein Adjektiv." },
    { question: "wohnen", options: ["Artikel", "Nomen", "Adjektiv", "Verb"], answer: "Verb", explanation: "wohnen ist ein Verb." },
    { question: "schnell", options: ["Artikel", "Nomen", "Adjektiv", "Verb"], answer: "Adjektiv", explanation: "schnell ist hier ein Adjektiv." },
    { question: "helfen", options: ["Artikel", "Nomen", "Adjektiv", "Verb"], answer: "Verb", explanation: "helfen ist ein Verb." },
    { question: "Wort", options: ["Artikel", "Nomen", "Adjektiv", "Verb"], answer: "Nomen", explanation: "Wort ist ein Nomen." },
    { question: "Zeit", options: ["Artikel", "Nomen", "Adjektiv", "Verb"], answer: "Nomen", explanation: "Zeit ist ein Nomen." },
    { question: "lernen", options: ["Artikel", "Nomen", "Adjektiv", "Verb"], answer: "Verb", explanation: "lernen ist ein Verb." },
    { question: "lesen", options: ["Artikel", "Nomen", "Adjektiv", "Verb"], answer: "Verb", explanation: "lesen ist ein Verb." },
    { question: "schreiben", options: ["Artikel", "Nomen", "Adjektiv", "Verb"], answer: "Verb", explanation: "schreiben ist ein Verb." },
    { question: "stehen", options: ["Artikel", "Nomen", "Adjektiv", "Verb"], answer: "Verb", explanation: "stehen ist ein Verb." },
    { question: "sitzen", options: ["Artikel", "Nomen", "Adjektiv", "Verb"], answer: "Verb", explanation: "sitzen ist ein Verb." },
    { question: "kommen", options: ["Artikel", "Nomen", "Adjektiv", "Verb"], answer: "Verb", explanation: "kommen ist ein Verb." },
    { question: "finden", options: ["Artikel", "Nomen", "Adjektiv", "Verb"], answer: "Verb", explanation: "finden ist ein Verb." },
    { question: "arbeiten", options: ["Artikel", "Nomen", "Adjektiv", "Verb"], answer: "Verb", explanation: "arbeiten ist ein Verb." },
    { question: "schwimmen", options: ["Artikel", "Nomen", "Adjektiv", "Verb"], answer: "Verb", explanation: "schwimmen ist ein Verb." },
    { question: "Freund", options: ["Artikel", "Nomen", "Adjektiv", "Verb"], answer: "Nomen", explanation: "Freund ist ein Nomen." },
    { question: "Regen", options: ["Artikel", "Nomen", "Adjektiv", "Verb"], answer: "Nomen", explanation: "Regen ist ein Nomen." },
    { question: "Fenster", options: ["Artikel", "Nomen", "Adjektiv", "Verb"], answer: "Nomen", explanation: "Fenster ist ein Nomen." },
    { question: "Milch", options: ["Artikel", "Nomen", "Adjektiv", "Verb"], answer: "Nomen", explanation: "Milch ist ein Nomen." },
    { question: "Vater", options: ["Artikel", "Nomen", "Adjektiv", "Verb"], answer: "Nomen", explanation: "Vater ist ein Nomen." },
    { question: "Mutter", options: ["Artikel", "Nomen", "Adjektiv", "Verb"], answer: "Nomen", explanation: "Mutter ist ein Nomen." },
    { question: "jung", options: ["Artikel", "Nomen", "Adjektiv", "Verb"], answer: "Adjektiv", explanation: "jung ist ein Adjektiv." },
    { question: "kalt", options: ["Artikel", "Nomen", "Adjektiv", "Verb"], answer: "Adjektiv", explanation: "kalt ist ein Adjektiv." },
    { question: "warm", options: ["Artikel", "Nomen", "Adjektiv", "Verb"], answer: "Adjektiv", explanation: "warm ist ein Adjektiv." },
    { question: "hoch", options: ["Artikel", "Nomen", "Adjektiv", "Verb"], answer: "Adjektiv", explanation: "hoch ist ein Adjektiv." },
    { question: "neu", options: ["Artikel", "Nomen", "Adjektiv", "Verb"], answer: "Adjektiv", explanation: "neu ist ein Adjektiv." }
  ]
};
